### ISSUE TITLE
consider a logData call (and support for markers)

### ISSUE THREAD

**Issue by pq** [pq/logs#4]
From https://github.com/pq/logs/pull/3#pullrequestreview-159055952:

> I wonder if we should have both a log() call and a logData() call. Are we ok with only being able to log objects (jsonable objects), or do we want the ability to log string messages as well?

Regarding markers:

> For a data pipeline for tools, just logging objects works. But people may want to log marker events as well:

```
log.log('cache', 'evicting $number cache entries');
log.logData('cache', entries.first);
...
log.logData('cache', entries.last);
```

**Comment by pq** [comment]
Since Strings json encodable I was imagining we didn't need a special case.  That is, we would just do something like:

    log('cache', () => 'evicting $number cache entries');

for that matter if the entries are encodable, those would just look like:

    log('cache', () => entries.first);
    ...
    log('cache', () => entries.last);

I'm not sure what `logData` gets us?

One answer is markers and that's a really interesting idea.  @stereotype441 showed me a tracing tool a while ago that took the idea even further and supported a kind of stack model so that nesting could be supported naturally with pushed (and popped) states.  Great food for thought as we flesh out some concrete examples.  (I wonder if `redux` in particular might benefit from something like this...)

**Comment by devoncarew** [comment]
I think also covered by the data logging PR? We can now log strings, w/o them being json encoded, and can log structured data as well when desired. Speculatively closing.

**Comment by pq** [comment]
We've got support for data logging now.  We don't have explicit support for "markers" but we can revisit that.  Closing for now...
